EndPoints MVP completed
learn-academy-2023-india/cat-tinder-backend-calico-aka-catmen pull request #2
Opened 2024-02-05 22:12 UTC by irvinmoore

2024-02-05 23:14 UTC, sjproctor reviewed
just fix the indentation please!

2024-02-05 23:14 UTC, sjproctor commented on app/controllers/cats_controller.rb
> +    end
Please fix your indentation on this file please.

2024-02-06 01:21 UTC, sjproctor approved these changes

2024-02-06 01:22 UTC, sjproctor requested changes
Are your tests passing?

2024-02-06 03:44 UTC, sjproctor approved these changes

2024-02-06 17:38 UTC, merged

2024-02-06 18:15 UTC, irvinmoore commented
Thank you.